server:
  port: 8097
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/company_service
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true
  application:
    name: company-service
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka