server:
  port: 8097
spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: 'test-client'
          client-secret: 'test-client'
          username: 'company'
          custom-auth: true
  main:
    allow-bean-definition-overriding: true
  application:
    name: company-service
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka